FROM mysql:8.0

COPY db_level1.sql /docker-entrypoint-initdb.d/db_level1.sql
COPY db_level2.sql /docker-entrypoint-initdb.d/db_level2.sql
COPY db_level3.sql /docker-entrypoint-initdb.d/db_level3.sql
COPY db_level4.sql /docker-entrypoint-initdb.d/db_level4.sql
COPY db_level5.sql /docker-entrypoint-initdb.d/db_level5.sql
